hmrc/vat-correspondence-details-frontend

conf/prod.routes, test/views/errors/agent/NotAuthorisedForClientViewSpec.scala
Reverts hmrc/vat-correspondence-details-frontend#15
=> Revert "BTAT-4175 Updated prod route"

app/config/frontendAppConfig.scala, app/connectors/httpParsers/CreateEmailVerificationRequestHttpParser.scala, app/connectors/httpParsers/GetCustomerInfoHttpParser.scala, app/connectors/httpParsers/GetEmailVerificationStateHttpParser.scala, app/connectors/httpParsers/UpdateEmailHttpParser.scala, app/controllers/ConfirmEmailController.scala, app/controllers/VerifyEmailController.scala, app/views/verify_email.scala.html, conf/app.routes, conf/logback.xml, test/assets/UpdateEmailConstants.scala, test/connectors/httpParsers/UpdateEmailHttpParserSpec.scala, test/controllers/ConfirmEmailControllerSpec.scala, test/controllers/VerifyEmailControllerSpec.scala, test/views/VerifyEmailViewSpec.scala
added creation of email verification into request, minor changes to parser logging, and set app origin
=> addVerificationRequestAndBits

app/common/SessionKeys.scala, app/controllers/ConfirmEmailController.scala, app/controllers/EmailChangeSuccessController.scala, test/controllers/ConfirmEmailControllerSpec.scala, test/controllers/EmailChangeSuccessControllerSpec.scala, test/controllers/HelloWorldControllerSpec.scala, test/controllers/VerifyEmailControllerSpec.scala, test/controllers/predicates/AuthoriseAsAgentWithClientSpec.scala, test/utils/TestUtil.scala
removed obsolete session keys and moved clearance of session to correct controller
=> codeReviewTweaks

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/govuk_wrapper.scala.html, conf/application.conf, test/mocks/MockAppConfig.scala
=> BTAT-4428 Implemented timeout config and javascript

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/controllers/VerifyEmailController.scala, app/forms/FeatureSwitchForm.scala, app/models/FeatureSwitchModel.scala, app/services/EmailVerificationService.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/views/featureSwitch.scala.html, conf/application.conf, conf/testOnly.routes, test/config/features/FeatureSpec.scala, test/services/EmailVerificationServiceSpec.scala
Please ensure this is merged first:
=> BTAT-4484 Added feature switch for email verification service

app/controllers/predicates/InflightPPOBPredicate.scala, build.sbt, test/config/features/FeatureSpec.scala, test/controllers/CaptureEmailControllerSpec.scala, test/controllers/ConfirmEmailControllerSpec.scala, test/controllers/ControllerBaseSpec.scala, test/controllers/SignOutControllerSpec.scala, test/controllers/VerifyEmailControllerSpec.scala, test/controllers/predicates/InflightPPOBPredicateSpec.scala, test/mocks/MockAuth.scala, test/services/EmailVerificationServiceSpec.scala, test/services/VatSubscriptionServiceSpec.scala, test/utils/TestUtil.scala, test/views/CaptureEmailViewSpec.scala, test/views/ConfirmEmailViewSpec.scala, test/views/EmailChangeSuccessViewSpec.scala, test/views/VerifyEmailViewSpec.scala
There are several small improvements to test specs here that were changed as part of my troubleshooting process with the vague error I was battling yesterday. Let me know if you have any questions regarding the changes.
=> BTAT-4546 Refactored InflightPPOBPredicate to not call auth

app/controllers/ConfirmWebsiteController.scala, app/views/ConfirmWebsiteView.scala.html, conf/app.routes, conf/messages, test/controllers/ConfirmWebsiteControllerSpec.scala, test/mocks/MockVatSubscriptionService.scala, test/services/VatSubscriptionServiceSpec.scala, test/utils/TestUtil.scala, test/views/CaptureWebsiteViewSpec.scala
I've left a test in commented out as it will be required as part of the story.
=> BTAT-6303: Added confirm website address route, controller and view

app/common/SessionKeys.scala, app/controllers/CaptureWebsiteController.scala, app/views/CaptureWebsiteView.scala.html, app/views/ConfirmWebsiteView.scala.html, conf/messages, test/controllers/CaptureWebsiteControllerSpec.scala, test/views/CaptureWebsiteViewSpec.scala, test/views/ConfirmWebsiteViewSpec.scala
A few things I've done:-
1. corrected the messages for ConfirmWebsiteView
2. added a viewspec for it
3. built submit function for CaptureWebsiteController
4. added current email on ConfirmWebsiteView (pulled from session)
=> Created submit for CaptureWebsiteController

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/config/frontendAppConfig.scala, app/forms/FeatureSwitchForm.scala, app/models/FeatureSwitchModel.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/views/FeatureSwitch.scala.html, app/views/email/CaptureEmailView.scala.html, app/views/landlineNumber/CaptureLandlineNumberView.scala.html, app/views/mobileNumber/CaptureMobileNumberView.scala.html, app/views/templates/ChangeSuccessView.scala.html, app/views/website/CaptureWebsiteView.scala.html, conf/application.conf, it/helpers/SessionCookieBaker.scala, test/mocks/MockAppConfig.scala, test/utils/TestUtil.scala, test/views/email/CaptureEmailViewSpec.scala, test/views/landlineNumber/CaptureLandlineNumberViewSpec.scala, test/views/mobileNumber/CaptureMobileNumberViewSpec.scala, test/views/templates/ChangeSuccessViewSpec.scala, test/views/website/CaptureWebsiteViewSpec.scala
Please ensure the following PRs are merged too:
- https://github.com/hmrc/app-config-base/pull/3713
- https://github.com/hmrc/app-config-production/pull/7325
- The relevant acceptance test PR
=> BTAT-7961 Added BTA entry point feature; made bookend links dynamic

app/common/SessionKeys.scala, app/controllers/contactPreference/EmailPreferenceConfirmationController.scala, app/controllers/contactPreference/EmailPreferenceController.scala, app/controllers/contactPreference/EmailToUseController.scala, it/pages/BasePageISpec.scala, it/pages/contactPreference/EmailPreferenceConfirmationPageSpec.scala, it/pages/contactPreference/EmailPreferencePageSpec.scala, it/pages/contactPreference/EmailToUsePageSpec.scala, test/controllers/contactPreference/EmailPreferenceConfirmationControllerSpec.scala, test/controllers/contactPreference/EmailPreferencesControllerSpec.scala, test/controllers/contactPreference/EmailToUseControllerSpec.scala
Reverts hmrc/vat-correspondence-details-frontend#197
=> [DM] [BTAT-7970] Wired individual components together

app/views/templates/ChangeSuccessView.scala.html, conf/messages, conf/messages.cy
To go in alongside https://github.com/hmrc/change-vat-details-acceptance-tests/pull/122
=> BTAT-8065 - Updated email confirmation screen

app/controllers/BaseController.scala, app/controllers/contactPreference/ContactPreferenceRedirectController.scala, app/controllers/contactPreference/EmailPreferenceController.scala, app/controllers/contactPreference/EmailToUseController.scala, app/controllers/contactPreference/LetterPreferenceController.scala, app/controllers/email/ConfirmEmailController.scala, app/controllers/landlineNumber/ConfirmLandlineNumberController.scala, app/controllers/mobileNumber/ConfirmMobileNumberController.scala, app/controllers/predicates/inflight/InFlightPredicate.scala, app/controllers/website/ConfirmWebsiteController.scala, app/models/customerInformation/PendingChanges.scala, app/views/errors/InFlightChangeView.scala.html, conf/messages, conf/messages.cy, it/pages/contactPreference/ContactPreferenceRedirectPageSpec.scala, it/pages/contactPreference/EmailPreferencePageSpec.scala, it/pages/contactPreference/EmailToUsePageSpec.scala, it/pages/contactPreference/LetterPreferencePageSpec.scala, test/assets/CustomerInfoConstants.scala, test/controllers/landlineNumber/ConfirmLandlineNumberControllerSpec.scala, test/controllers/mobileNumber/ConfirmMobileNumberControllerSpec.scala, test/controllers/predicates/inflight/InFlightPredicateSpec.scala, test/mocks/MockAuth.scala, test/models/customerInformation/PendingChangesSpec.scala, test/views/errors/InFlightChangeViewSpec.scala
I also removed the JSON writes from `PendingChanges` as it is not required. This work also needs the following AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/123
=> BTAT-8078 Extended functionality of inflight predicate and updated error page

app/controllers/contactPreference/AddEmailAddressController.scala, app/controllers/contactPreference/EmailPreferenceController.scala, app/views/contactPreference/AddEmailAddressView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/pages/contactPreference/AddEmailAddressPage.scala, it/pages/contactPreference/EmailPreferencePageSpec.scala, it/stubs/VatSubscriptionStub.scala, test/assets/ContactPrefAddEmailMessages.scala, test/controllers/contactPreference/AddEmailAddressControllerSpec.scala, test/controllers/contactPreference/EmailPreferenceControllerSpec.scala, test/views/contactPreference/AddEmailAddressViewSpec.scala
=> BTAT-8058 Adding new view/controller

app/controllers/contactPreference/AddEmailAddressController.scala, app/controllers/contactPreference/ChangeEmailController.scala, conf/app.routes, it/pages/contactPreference/AddEmailAddressPage.scala, test/controllers/contactPreference/AddEmailAddressControllerSpec.scala, test/controllers/contactPreference/ChangeEmailControllerSpec.scala
Also added stub action for change email for routing purposes
For review only, please don't merge until BTAT-8058 is in
=> Added submit action for AddEmailAddressController

app/views/email/CaptureEmailView.scala.html, app/views/landlineNumber/CaptureLandlineNumberView.scala.html, app/views/mobileNumber/CaptureMobileNumberView.scala.html, app/views/templates/inputs/Text.scala.html, app/views/website/CaptureWebsiteView.scala.html, test/views/email/CaptureEmailViewSpec.scala, test/views/landlineNumber/CaptureLandlineNumberViewSpec.scala, test/views/mobileNumber/CaptureMobileNumberViewSpec.scala, test/views/templates/inputs/TextHelperSpec.scala, test/views/website/CaptureWebsiteViewSpec.scala
Please do not merge until BTAT-8136 is completed
=> [BTAT-8125] Removed extraneous labels

app/views/email/CaptureEmailView.scala.html, conf/application.conf, test/views/email/CaptureEmailViewSpec.scala
Rebased this morning (14/08) but might need it again before merge (let me know before merging)
Do not merge until pipeline is clear
=> BTAT-8210 Fix for back link & minor test structure amendment

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/forms/FeatureSwitchForm.scala, app/models/FeatureSwitchModel.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/views/FeatureSwitch.scala.html, conf/application.conf
Please review together with https://github.com/hmrc/app-config-production/pull/8437#issue-492961480
=> [BTAT-8415] Added feature switch

app/controllers/landlineNumber/ConfirmRemoveLandlineController.scala, app/forms/RemovalForm.scala, app/views/landlineNumber/ConfirmRemoveLandlineView.scala.html, conf/app.routes, conf/application.conf, test/controllers/landlineNumber/ConfirmRemoveLandlineControllerSpec.scala, test/forms/RemovalFormSpec.scala, test/views/landlineNumber/ConfirmRemoveLandlineViewSpec.scala
This PR on the performance tests also needs to be merged: https://github.com/hmrc/change-vat-details-performance-tests/pull/50
=> [BTAT-8263] Updated remove landline journey with CSRF protection

app/controllers/email/ConfirmEmailController.scala, app/controllers/email/VerifyEmailController.scala, app/controllers/email/VerifyPasscodeController.scala, conf/app.routes, test/controllers/email/VerifyEmailControllerSpec.scala, test/controllers/email/VerifyPasscodeControllerSpec.scala, test/utils/TestUtil.scala
Don't merge until the change-vat-details-acceptance tests have been updated.
=> BTAT-8416 Adding controller for email passcode journey

app/controllers/email/VerifyPasscodeController.scala, app/views/email/PasscodeErrorView.scala.html, it/pages/email/PasscodePageSpec.scala, it/stubs/EmailVerificationStub.scala, test/controllers/email/VerifyPasscodeControllerSpec.scala
Unable to test this manually yet but hopefully the tests demonstrate the functionality clearly.
=> BTAT-8505 Catered for PASSCODE_MISTMATCH scenario

app/views/contactPreference/AddEmailAddressView.scala.html, test/views/contactPreference/AddEmailAddressViewSpec.scala
AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/144
=> BTAT-9196 Updating AddEmailAddressView to use govUk assets

app/views/errors/InFlightChangeView.scala.html, app/views/errors/NotSignedUpView.scala.html, app/views/errors/SessionTimeoutView.scala.html, app/views/errors/agent/AgentJourneyDisabledView.scala.html, app/views/errors/agent/UnauthorisedAgentView.scala.html, test/views/errors/InFlightChangeViewSpec.scala, test/views/errors/NotSignedUpViewSpec.scala, test/views/errors/SessionTimeoutViewSpec.scala, test/views/errors/agent/AgentJourneyDisabledViewSpec.scala, test/views/errors/agent/UnauthorisedAgentViewSpec.scala
=> BTAT-9203 Migrated error views to GOVUK assets

app/views/mobileNumber/CaptureMobileNumberView.scala.html, app/views/mobileNumber/ConfirmRemoveMobileView.scala.html, test/views/mobileNumber/CaptureMobileNumberViewSpec.scala, test/views/mobileNumber/ConfirmRemoveMobileViewSpec.scala
AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/148
=> BTAT-9205 Migrated mobile number views to GOVUK assets

app/testOnly/views/FeatureSwitch.scala.html, app/testOnly/views/FeatureSwitchItems.scala
=> BTAT-9207 Migrated feature switch view to GOVUK assets

app/views/contactPreference/PreferenceConfirmationView.scala.html, test/controllers/contactPreference/ContactPreferenceConfirmationControllerSpec.scala, test/views/contactPreference/PreferenceConfirmationViewSpec.scala
AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/149
=> BTAT-9200 Updating contact pref confirmation view to use govUk assets

app/views/email/PasscodeErrorView.scala.html, app/views/email/PasscodeView.scala.html, it/pages/email/PasscodePageSpec.scala, test/views/email/PasscodeErrorViewSpec.scala, test/views/email/PasscodeViewSpec.scala
AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/150
=> [BTAT-9202] Passcode view govuk assets

app/views/website/CaptureWebsiteView.scala.html, app/views/website/ConfirmRemoveWebsiteView.scala.html, test/views/website/CaptureWebsiteViewSpec.scala, test/views/website/ConfirmRemoveWebsiteViewSpec.scala
AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/152
=> BTAT-9206 Updating Website Views to use govuk assets

app/assets/stylesheets/application.scss, app/views/templates/ChangeSuccessView.scala.html, app/views/templates/CheckYourAnswersView.scala.html, app/views/templates/UpdateClient.scala.html, test/controllers/email/ConfirmEmailControllerSpec.scala, test/controllers/email/EmailChangeSuccessControllerSpec.scala, test/views/templates/ChangeSuccessViewSpec.scala, test/views/templates/CheckYourAnswersViewSpec.scala
ATs: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/153
=> [BTAT-9208] Change success and CYA views govuk assets

app/controllers/website/ConfirmRemoveWebsiteController.scala, app/views/website/ConfirmRemoveWebsiteView.scala.html, build.sbt, conf/app.routes, conf/messages, conf/messages.cy, test/controllers/website/ConfirmRemoveWebsiteControllerSpec.scala, test/views/website/ConfirmRemoveWebsiteViewSpec.scala
This will need to be merged with https://github.com/hmrc/change-vat-details-acceptance-tests/pull/178
=> BTAT-9829 Updating website removal content

app/common/SessionKeys.scala, app/config/frontendAppConfig.scala, app/controllers/ChangeSuccessController.scala, app/controllers/email/BouncedEmailController.scala, app/controllers/email/ConfirmEmailController.scala, app/controllers/email/VerifyPasscodeController.scala, app/views/email/BouncedEmailView.scala.html, app/views/email/CaptureEmailView.scala.html, app/views/email/PasscodeView.scala.html, conf/messages, conf/messages.cy, test/controllers/ChangeSuccessControllerSpec.scala, test/controllers/email/BouncedEmailControllerSpec.scala, test/controllers/email/ConfirmEmailControllerSpec.scala, test/controllers/email/VerifyPasscodeControllerSpec.scala, test/views/email/BouncedEmailViewSpec.scala, test/views/email/CaptureEmailViewSpec.scala, test/views/email/PasscodeViewSpec.scala
Also fixed what appears to be a small bug in `ChangeSuccessController` where it was using the wrong app config value (the host instead of the full path).
=> BTAT-10288 Made dynamic breadcrumbs and back links for fix email journey

app/views/email/PasscodeView.scala.html, build.sbt, test/views/email/PasscodeViewSpec.scala
No need for the whole span/h2 question, the form was simply not being used correctly
=> BTAT-10384 Corrected HTML for passcode input label/hint

build.sbt, conf/messages, conf/messages.cy, test/connectors/httpParsers/CreateEmailVerificationRequestHttpParserSpec.scala, test/connectors/httpParsers/GetEmailVerificationStateHttpParserSpec.scala, test/connectors/httpParsers/UpdateEmailHttpParserSpec.scala, test/connectors/httpParsers/UpdatePPOBHttpParserSpec.scala
Removed a few unused messages and addressed a Scalatest deprecation warning in a few of the HTTP parser tests
=> BTAT-10609 Audit of message files

conf/messages, conf/messages.cy, test/views/templates/CheckYourAnswersViewSpec.scala
Please review together with https://github.com/hmrc/change-vat-details-acceptance-tests/pull/217
=> [BTAT-11601] Updated heading message for CYA pages
